language: python

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: generic
      env: PYTHON_VERSION="2.7" PYTHON_ARCH="64"
      before_install:
          # Remove homebrew
          - |
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
                  chmod +x ~/uninstall_homebrew
                  ~/uninstall_homebrew -fq
                  rm ~/uninstall_homebrew
              fi
          - |
              MINICONDA_URL="https://repo.continuum.io/miniconda"
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
              else
                  MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
              fi
              curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
              bash $MINICONDA_FILE -b
          - export PATH=/Users/travis/miniconda3/bin:$PATH
    - os: osx
      osx_image: xcode8.3
      language: generic
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="64"
      before_install:
          # Remove homebrew
          - |
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
                  chmod +x ~/uninstall_homebrew
                  ~/uninstall_homebrew -fq
                  rm ~/uninstall_homebrew
              fi
          - |
              MINICONDA_URL="https://repo.continuum.io/miniconda"
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
              else
                  MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
              fi
              curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
              bash $MINICONDA_FILE -b
          - export PATH=/Users/travis/miniconda3/bin:$PATH
    - os: osx
      osx_image: xcode8.3
      language: generic
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="64"
      before_install:
          # Remove homebrew
          - |
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
                  chmod +x ~/uninstall_homebrew
                  ~/uninstall_homebrew -fq
                  rm ~/uninstall_homebrew
              fi
          - |
              MINICONDA_URL="https://repo.continuum.io/miniconda"
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
              else
                  MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
              fi
              curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
              bash $MINICONDA_FILE -b
          - export PATH=/Users/travis/miniconda3/bin:$PATH
    - os: osx
      osx_image: xcode8.3
      language: generic
      env: PYTHON_VERSION="3.7" PYTHON_ARCH="64"
      before_install:
          # Remove homebrew
          - |
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
                  chmod +x ~/uninstall_homebrew
                  ~/uninstall_homebrew -fq
                  rm ~/uninstall_homebrew
              fi
          - |
              MINICONDA_URL="https://repo.continuum.io/miniconda"
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
              else
                  MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
              fi
              curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
              bash $MINICONDA_FILE -b
          - export PATH=/Users/travis/miniconda3/bin:$PATH
    - os: linux
      env: PYTHON_VERSION="2.7" PYTHON_ARCH="64"
      before_install:
          - |
              MINICONDA_URL="https://repo.continuum.io/miniconda"
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
              else
                  MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
              fi
              curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
              bash $MINICONDA_FILE -b
          - export PATH=/home/travis/miniconda3/bin:$PATH
    - os: linux
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="64"
      before_install:
          - |
              MINICONDA_URL="https://repo.continuum.io/miniconda"
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
              else
                  MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
              fi
              curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
              bash $MINICONDA_FILE -b
          - export PATH=/home/travis/miniconda3/bin:$PATH
    - os: linux
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="64"
      before_install:
          - |
              MINICONDA_URL="https://repo.continuum.io/miniconda"
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
              else
                  MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
              fi
              curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
              bash $MINICONDA_FILE -b
          - export PATH=/home/travis/miniconda3/bin:$PATH
    - os: linux
      env: PYTHON_VERSION="3.7" PYTHON_ARCH="64"
      before_install:
          - |
              MINICONDA_URL="https://repo.continuum.io/miniconda"
              if [ "$TRAVIS_OS_NAME" = "osx" ]; then
                  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
              else
                  MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
              fi
              curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
              bash $MINICONDA_FILE -b
          - export PATH=/home/travis/miniconda3/bin:$PATH
    # - os: windows
      # language: sh
      # env: PYTHON_VERSION="2.7" PYTHON_ARCH="32" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      # filter_secrets: false
      # before_install:
          # - choco install openssl.light --forcex86
          # - choco install miniconda3 --params="'/AddToPath:1'" --forcex86
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="32" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light --forcex86
          - choco install miniconda3 --params="'/AddToPath:1'" --forcex86
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="32" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light --forcex86
          - choco install miniconda3 --params="'/AddToPath:1'" --forcex86
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.7" PYTHON_ARCH="32" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light --forcex86
          - choco install miniconda3 --params="'/AddToPath:1'" --forcex86
    # - os: windows
      # language: sh
      # env: PYTHON_VERSION="2.7" PYTHON_ARCH="64" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      # filter_secrets: false
      # before_install:
          # - choco install openssl.light
          # - choco install miniconda3 --params="'/AddToPath:1'"
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="64" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light
          - choco install miniconda3 --params="'/AddToPath:1'"
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="64" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light
          - choco install miniconda3 --params="'/AddToPath:1'"
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.7" PYTHON_ARCH="64" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light
          - choco install miniconda3 --params="'/AddToPath:1'"

install:
    - conda config --set always_yes yes --set changeps1 no --set ssl_verify no --set anaconda_upload no
    - source "conda/conda_install.sh"
    # Configure MacOSX SDK
    - |
        if [ "$TRAVIS_OS_NAME" = "osx" ]; then
            echo -e "CONDA_BUILD_SYSROOT:\n    - $(xcrun --sdk macosx --show-sdk-path) # [osx]" > $HOME/conda_build_config.yaml
            cat $HOME/conda_build_config.yaml
        fi

script:
  - python --version
  - conda install --yes --quiet conda-build && conda install --yes --quiet anaconda-client
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - bash conda/conda_build.sh
  - echo "Build successful."
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then bash conda/conda_upload.sh; fi

notifications:
    email: false
