matrix:
  include:
    - os: windows
      language: sh
      env: PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH" PYTHON_VERSION="3.6" PYTHON_ARCH="64"
      filter_secrets: false
      before_install:
          - choco install openssl.light
          - choco install miniconda3 --params="'/AddToPath:1'"

install:
    - conda config --set always_yes yes --set changeps1 no --set ssl_verify no --set anaconda_upload yes
    - source "conda/conda_install.sh"

script:
  # Your test script goes here
  - python --version
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash conda/conda_upload.sh

notifications:
    email: false
