language: python

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      language: generic
      env: PYTHON_VERSION="2.7" PYTHON_ARCH="64"
      before_install:
          - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
          - chmod +x miniconda.sh
          - ./miniconda.sh -b
          - export PATH=/Users/travis/miniconda3/bin:$PATH
    - os: osx
      osx_image: xcode6.4
      language: generic
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="64"
      before_install:
          - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
          - chmod +x miniconda.sh
          - ./miniconda.sh -b
          - export PATH=/Users/travis/miniconda3/bin:$PATH
    - os: osx
      osx_image: xcode6.4
      language: generic
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="64"
      before_install:
          - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
          - chmod +x miniconda.sh
          - ./miniconda.sh -b
          - export PATH=/Users/travis/miniconda3/bin:$PATH
    - os: osx
      osx_image: xcode6.4
      language: generic
      env: PYTHON_VERSION="3.7" PYTHON_ARCH="64"
      before_install:
          - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
          - chmod +x miniconda.sh
          - ./miniconda.sh -b
          - export PATH=/Users/travis/miniconda3/bin:$PATH
    - os: linux
      env: PYTHON_VERSION="2.7" PYTHON_ARCH="64"
      before_install:
          - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          - chmod +x miniconda.sh
          - ./miniconda.sh -b
          - export PATH=/home/travis/miniconda3/bin:$PATH
    - os: linux
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="64"
      before_install:
          - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          - chmod +x miniconda.sh
          - ./miniconda.sh -b
          - export PATH=/home/travis/miniconda3/bin:$PATH
    - os: linux
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="64"
      before_install:
          - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          - chmod +x miniconda.sh
          - ./miniconda.sh -b
          - export PATH=/home/travis/miniconda3/bin:$PATH
    - os: linux
      env: PYTHON_VERSION="3.7" PYTHON_ARCH="64"
      before_install:
          - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          - chmod +x miniconda.sh
          - ./miniconda.sh -b
          - export PATH=/home/travis/miniconda3/bin:$PATH
    # - os: windows
      # language: sh
      # env: PYTHON_VERSION="2.7" PYTHON_ARCH="32" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      # filter_secrets: false
      # before_install:
          # - choco install openssl.light --forcex86
          # - choco install miniconda3 --params="'/AddToPath:1'" --forcex86
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="32" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light --forcex86
          - choco install miniconda3 --params="'/AddToPath:1'" --forcex86
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="32" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light --forcex86
          - choco install miniconda3 --params="'/AddToPath:1'" --forcex86
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.7" PYTHON_ARCH="32" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light --forcex86
          - choco install miniconda3 --params="'/AddToPath:1'" --forcex86
    # - os: windows
      # language: sh
      # env: PYTHON_VERSION="2.7" PYTHON_ARCH="64" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      # filter_secrets: false
      # before_install:
          # - choco install openssl.light
          # - choco install miniconda3 --params="'/AddToPath:1'"
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="64" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light
          - choco install miniconda3 --params="'/AddToPath:1'"
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="64" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light
          - choco install miniconda3 --params="'/AddToPath:1'"
    - os: windows
      language: sh
      env: PYTHON_VERSION="3.7" PYTHON_ARCH="64" PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:/c/tools/miniconda3/envs/testenv/Lib/site-packages/rdkit:$PATH"
      filter_secrets: false
      before_install:
          - choco install openssl.light
          - choco install miniconda3 --params="'/AddToPath:1'"

install:
    - conda config --set always_yes yes --set changeps1 no --set ssl_verify no --set anaconda_upload no
    - source "conda/conda_install.sh"

script:
  # Your test script goes here
  - python --version
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash conda/conda_upload.sh

notifications:
    email: false
