{% set name = "helics" %}
{% set version = "2.6.1.post0.dev0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  features:
    - vc9  [win and py27]
    - vc10 [win and py34]
    - vc14 [win and py>=35]

source:
  - git_url: https://github.com/GMLC-TDC/HELICS-src
    git_rev: v2.6.1
    folder: helics
  - git_url: https://github.com/GMLC-TDC/pyhelics
    git_rev: v{{ version }}
    folder: pyhelics

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake >=3.4.0
    - boost-cpp
    - zeromq [not win]
    - python {{ python }}
    - pip
    - setuptools
    - enum34 [py27]
  run:
    - zeromq [not win]
    - python {{ python }}
    - cffi
    - enum34 [py27]

about:
  home: "https://github.com/GMLC-TDC/HELICS"
  license: BSD
  license_family: BSD
  license_file:
  summary: "Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS)"
  description: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  doc_url: https://helics.readthedocs.io/en/latest/
  dev_url: https://github.com/GMLC-TDC/HELICS

extra:
  recipe-maintainers:
    - kdheepak
