{% set name = "helics" %}
{% set version = "3.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b1bda3415c6c47c76be92854c1a5e18953954e2d7e4f545e1b621a1727b13258

build:
  number: 0
  script:
    - "{{ PYTHON }} scripts/download-ziptools.py"
    - "{{ PYTHON }} setup.py download"
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - cffi >=1.6.0
    - pip
    - python
    - zeromq
  run:
    - cffi >=1.6.0
    - python
    - zeromq

test:
  imports:
    - helics

about:
  home: "https://github.com/GMLC-TDC/pyhelics"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python HELICS bindings"
  doc_url: "https://python.helics.org/"
  dev_url: "https://python.helics.org/"

extra:
  recipe-maintainers:
    - kdheepak
