{% set name = "helics" %}
{% set version = "2.6.1.post0.dev0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0

source:
  - git_url: https://github.com/GMLC-TDC/HELICS-src
    folder: helics
  - git_url: https://github.com/GMLC-TDC/pyhelics
    folder: pyhelics
  - git_url: https://github.com/abarker/strip-hints
    folder: strip_hints

requirements:
  build:
    - {{ compiler('c') }}       # [not win]
    - {{ compiler('cxx') }}     # [not win]
    - mingw                     # [win]
    - m2w64-toolchain           # [win]
    - boost-cpp                 # [not win]
    - libboost-mingw            # [win]
    - ninja
    - cmake >=3.4.0
    - python
    - pip
    - setuptools
    - zeromq [not win]
    - python {{python}}
    - enum34 [py27]
  run:
    - zeromq [not win]
    - python {{python}}
    - cffi
    - enum34 [py27]

test:
  commands:
    - python -c "import helics"

about:
  home: "https://github.com/GMLC-TDC/HELICS"
  license: BSD
  license_family: BSD
  license_file:
  summary: "Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS)"
  description: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  doc_url: https://helics.readthedocs.io/en/latest/
  dev_url: https://github.com/GMLC-TDC/HELICS

extra:
  recipe-maintainers:
    - kdheepak
