{% set name = "helics" %}
{% set version = "3.1.2.post1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b40824c2ffd69a1cc2d3b34f75b2beabf04e44e453835040e86a7ebec6f27eb5

build:
  number: 0
  script:
    - "{{ PYTHON }} setup.py download"
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - cffi >=1.6.0
    - pip
    - python
    - zeromq
  run:
    - cffi >=1.6.0
    - python
    - zeromq

test:
  imports:
    - helics
commands:
  - helics_app --help
  - helics_broker --help
  - helics_broker_server --help
  - helics_player --help
  - helics_recorder --help

about:
  home: "https://github.com/GMLC-TDC/pyhelics"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python HELICS bindings"
  doc_url: "https://python.helics.org/"
  dev_url: "https://python.helics.org/"

extra:
  recipe-maintainers:
    - kdheepak
