{% set name = "helics" %}
{% set version = "2.0.0" %}
{% set checksum = "73e24a09d59ae201e750ac287ab5ceb52c275e4ba6077d47274a9fafc612f2b5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GMLC-TDC/HELICS/archive/v2.0.0.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script_env:
      - CONDA_BLD_PATH

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.4.0
    - swig
    - ninja
    - boost-cpp
    - zeromq
    - python
  host:
    - python
    - boost-cpp
    - zeromq
  run:
    - python
    - boost-cpp
    - zeromq

test:
  imports:
    - helics

about:
  home: https://github.com/GMLC-TDC/HELICS
  license: BSD
  license_file: LICENSE
  license_family: BSD
  summary: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  description: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  doc_url: https://helics.readthedocs.io/en/latest/
  dev_url: https://github.com/GMLC-TDC/HELICS

extra:
  recipe-maintainers:
    - kdheepak
