{% set name = "helics" %}
{% set version = "2.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0

source:
  - url: https://github.com/GMLC-TDC/HELICS-src/archive/v{{ version }}.tar.gz
    folder: helics
  - git_url: https://github.com/GMLC-TDC/pyhelics
    folder: pyhelics

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.4.0
    - python
    - pip
    - setuptools
  run:
    - python
    - zeromq

test:
  imports:
    - helics

about:
  home: "https://github.com/GMLC-TDC/HELICS"
  license: BSD
  license_family: BSD
  license_file:
  summary: "Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS)"
  description: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  doc_url: https://helics.readthedocs.io/en/latest/
  dev_url: https://github.com/GMLC-TDC/HELICS

extra:
  recipe-maintainers:
    - kdheepak
