{% set name = "helics" %}
{% set version = "3.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 62f9ba78681db642796bd13992b804584ab526d616ea4dcb4a18a1136755041e

build:
  number: 0
  script:
    - "{{ PYTHON }} setup.py download"
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - cffi >=1.6.0
    - pip
    - python
    - zeromq
  run:
    - cffi >=1.6.0
    - python
    - zeromq

test:
  imports:
    - helics

about:
  home: "https://github.com/GMLC-TDC/pyhelics"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python HELICS bindings"
  doc_url: "https://python.helics.org/"
  dev_url: "https://python.helics.org/"

extra:
  recipe-maintainers:
    - kdheepak
