{% set name = "helics" %}
{% set version = "2.6.1.post5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 71d052cf1030a5548073ddf87235558ee7bb1ed286cb3a4bcfd144668acf72af

build:
  number: 0
  script:
    - "{{ PYTHON }} setup.py download"
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - cffi >=1.0.0
    - pip
    - python
    - zeromq
  run:
    - cffi >=1.0.0
    - python
    - zeromq

test:
  imports:
    - helics

about:
  home: "https://github.com/GMLC-TDC/pyhelics"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Python HELICS bindings"
  doc_url: "https://python.helics.org/"
  dev_url: "https://python.helics.org/"

extra:
  recipe-maintainers:
    - kdheepak
