{% set name = "helics" %}
{% set version = "2.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - helics

about:
  home: "https://github.com/GMLC-TDC/HELICS"
  license: BSD
  license_family: BSD
  license_file:
  summary: "Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS)"
  doc_url: https://helics.readthedocs.io/en/latest/
  dev_url: https://github.com/GMLC-TDC/HELICS

extra:
  recipe-maintainers:
    - kdheepak
