{% set name = "helics" %}
{% set version = "2.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: c1c9f28402866acf7fc9f075cbae6e0519d9c7867a8a3e71f7cd3c2575169be7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - helics

about:
  home: "https://github.com/GMLC-TDC/HELICS"
  license: BSD
  license_family: BSD
  license_file:
  summary: "Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS)"
  doc_url: https://helics.readthedocs.io/en/latest/
  dev_url: https://github.com/GMLC-TDC/HELICS

extra:
  recipe-maintainers:
    - kdheepak
