name: CI

on: [push]

jobs:
  build:
    name: Conda (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        auto-update-conda: true
        python-version: 3.8

    - name: Install conda packages
      shell: bash -l {0}
      run: |
        conda install --yes --quiet conda-build conda-verify anaconda-client

    - name: Build Conda Python package
      shell: bash -l {0}
      run: |
        export CONDA_BLD_PATH=$HOME/conda-bld
        conda-build helics

    - name: Conda package path
      shell: bash -l {0}
      run: |
        export CONDA_BLD_PATH=$HOME/conda-bld
        conda-build helics --output

    - name: Conda upload
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash -l {0}
      env:
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      run:
        export CONDA_BLD_PATH=$HOME/conda-bld
        anaconda -t $BINSTAR_TOKEN upload $(conda-build helics --output)
