name: CI

on: [push]

jobs:
  build:
    name: Conda (${{ matrix.os }} + ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        auto-update-conda: true
        python-version: ${{ matrix.python }}

    - name: Install conda packages
      shell: bash -l {0}
      run: |
        conda install --yes --quiet conda-build conda-verify anaconda-client

    - name: Build Conda Python package
      shell: bash -l {0}
      env:
        ANACONDA_API_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      run: |
        export CONDA_BLD_PATH=$HOME/conda-bld
        conda config --set anaconda_upload yes
        conda-build helics
    - name: Conda upload
      # if: startsWith(github.ref, 'refs/tags/')
      shell: bash -l {0}
      env:
        ANACONDA_API_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      run: |
        export CONDA_BLD_PATH=$HOME/conda-bld
        anaconda upload $(conda-build helics --output)
