name: CI

on: [push]

jobs:
  build:

    name: Conda (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.7

    - name: Build and upload conda package
      shell: bash -l {0}
      env:
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      run: |
        CONDA_BLD_PATH=$HOME/conda-bld
        export CONDA_BLD_PATH
        conda install --yes --quiet conda-build conda-verify
        conda install --yes --quiet anaconda-client
        conda-build . --output
        # anaconda -t $BINSTAR_TOKEN upload $(conda-build --python=3.8 . --output)
        # conda-build --python=3.7 .
        # anaconda -t $BINSTAR_TOKEN upload $(conda-build --python=3.7 . --output)
        # conda-build --python=3.6 .
        # anaconda -t $BINSTAR_TOKEN upload $(conda-build --python=3.6 . --output)
        # conda-build --python=2.7 .
        # anaconda -t $BINSTAR_TOKEN upload $(conda-build --python=2.7 . --output)
