name: CI

on: [push]

jobs:
  build:
    name: Conda (${{ matrix.os }} - ${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python_version: ['3.8', '3.7', '3.6', '2.7']

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python_version }}

    - name: Install conda packages
      shell: bash -l {0}
      env:
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      run: |
        conda install --yes --quiet conda-build conda-verify anaconda-client

    - name: Build Conda Python package
      shell: bash -l {0}
      env:
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      run: |
        export CONDA_BLD_PATH=$HOME/conda-bld
        conda-build --python=${{ matrix.python_version }} helics
        # anaconda -t $BINSTAR_TOKEN upload $(conda-build --python=${{ matrix.python_version }} helics --output)
