name: HELICS build
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-10.14, windows-2016, windows-2019, ubuntu-16.04, ubuntu-18.04]
        include:
          - os: ubuntu-16.04
            python-arch: "x64"
            python-version: "3.6.x" 
            install-headerfiles: true
            gcc-version: "5"
          - os: ubuntu-18.04
            python-arch: "x64"
            python-version: "3.6.x" 
            install-headerfiles: true
            gcc-version: "7"
          - os: macOS-10.14
            python-arch: "x64"
            python-version: "3.6.x" 
            install-headerfiles: false
          - os: windows-2016
            vs-version: 15
            python-arch: "x86"
            python-version: "3.6.x" 
            install-headerfiles: false
          - os: windows-2019
            vs-version: 16
            python-arch: "x86"
            python-version: "3.6.x" 
            install-headerfiles: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}
    - name: Install C and C++ header files
      run: |
        sudo apt-get update && sudo apt-get install -y gcc-multilib
      if: matrix.install-headerfiles
    - name: Install conda
      run: |
        python -m pip install --upgrade conda
