name: CI

on: [push]

jobs:
  build:

    name: Conda (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
        auto-update-conda: true
        python-version: 3.7

    - name: Build conda package
      shell: bash -l {0}
      run: |
        CONDA_BLD_PATH=$HOME/conda-bld
        export CONDA_BLD_PATH
        conda install --yes --quiet conda-build conda-verify
        conda install --yes --quiet anaconda-client
        # conda config --set anaconda_upload yes
        conda-build --python=3.7 .
        conda-build --python=3.6 .
        # conda-build --python=3.5 .
        conda-build --python=2.7 .

    - name: Upload conda package
      shell: bash -l {0}
      env:
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      run: |
        anaconda upload -t $BINSTAR_TOKEN -u gmlc-tdc $(conda-build --python=2.7 . --output)
        # anaconda upload -t $BINSTAR_TOKEN -u gmlc-tdc $(conda-build --python=3.5 . --output)
        anaconda upload -t $BINSTAR_TOKEN -u gmlc-tdc $(conda-build --python=3.6 . --output)
        anaconda upload -t $BINSTAR_TOKEN -u gmlc-tdc $(conda-build --python=3.7 . --output)
